version: '3.9'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
        user: '0:0'
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: PasswordO1
            MSSQL_PID: Express

    oracle:
        image: oracleinanutshell/oracle-xe-11g:latest
        ports:
            - 1521:1521
            - 5500:5500