version: '3.9'

services:

    user-serice-database:
      image: mysql:8.0.25
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database-user
            MYSQL_USER: database-user-username
            MYSQL_PASSWORD: database-user-password

    user-details-database:
        image: mysql:8.0.25
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database-details
            MYSQL_USER: database-details-username
            MYSQL_PASSWORD: database-details-password
        volumes:
            - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"